#!/bin/bash

ETC_HOSTS_PATH="/etc/hosts"

createYamlFromHostsFile() {
  doc="rules:"
  while IFS= read -r line; do
    # Skip empty lines and comments
    [[ -z "$line" || "$line" == \#* ]] && continue

    read -ra fields <<< "$line"

    ip="${fields[0]}"

    for ((i=1; i<${#fields[@]}; i++)); do
      host="${fields[i]}"
      [[ $ip == "#" || $host == "#" ]] && break
      createDocLine "static" "$host" "$ip"
    done

  done < "$ETC_HOSTS_PATH"
  echo -e "$doc$_doc"
}

createDocLine() {
  local type="$1"
  local pattern="$2"
  local target="$3"
  _doc=$_doc"\n  - type: $type\n    pattern: $pattern\n    options:\n      target: $target"
}


createYamlFromHostsFile